USE [master]
GO

/****** Object:  Database [Hobbes]    Script Date: 11/20/2016 5:11:37 PM ******/
CREATE DATABASE [Hobbes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hobbes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Hobbes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Hobbes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Hobbes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Hobbes] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hobbes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hobbes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hobbes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hobbes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hobbes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hobbes] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hobbes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hobbes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hobbes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hobbes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hobbes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hobbes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hobbes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hobbes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hobbes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hobbes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hobbes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hobbes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hobbes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hobbes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hobbes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hobbes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hobbes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hobbes] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Hobbes] SET  MULTI_USER 
GO

ALTER DATABASE [Hobbes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hobbes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hobbes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hobbes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Hobbes] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Hobbes] SET QUERY_STORE = OFF
GO

USE [Hobbes]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Hobbes] SET  READ_WRITE 
GO


